### ISSUE TITLE
[BUG]: Apigear plugins not working in UE 5.3 and 5.2

### ISSUE THREAD

**Issue by dorotaphanSiili** [apigear-io/template-unreal#107]
### Description of the bug

when trying to build the plugins with vs2019 for the UE5.3 the error is:
```
Microsoft platform targets must be compiled with Visual Studio 2022 17.4 (MSVC 14.34.x) or later for the installed engine. Please update Visual Studio 2022 and ensure no configuration is forcing WindowsTargetRules.Compiler to VisualStudio2019. The current compiler version was detected as: 14.29.30154
Took 3.28s to run dotnet.exe, ExitCode=6
```
with vs2022:
`Error	MSB3073	The command "C:\UE_5.3\Engine\Build\BatchFiles\Build.bat MyProjectEditor Win64 Development -Project="C:\TEST_api\MyProject\MyProject.uproject" -WaitMutex -FromMsBuild" exited with code 6.	MyProject	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets	44`

for 5.2 the error is:

```
[37/47] Compile [x64] OLinkHostConnection.spec.cpp
D:\ws\apigear\template-unreal\goldenmaster\build\Plugins\ApiGear\HostProject\Plugins\ApiGear\Source\ApiGearOLink\Private\Tests\OLinkHostConnection.spec.cpp(48): error C3668: 'MockNetworkingWebSocket::GetUrlArgs': method with override specifier 'override' did not override any base class methods
D:\ws\apigear\template-unreal\goldenmaster\build\Plugins\ApiGear\HostProject\Plugins\ApiGear\Source\ApiGearOLink\Private\Tests\OLinkHostConnection.spec.cpp(52): error C3668: 'MockNetworkingWebSocket::GetUrlArgByName': method with override specifier 'override' did not override any base class methods
```

### Steps To Reproduce

install 5.3 or 5.2 UE
generate any apigear plugins
copy the Plugins folder into your UE project with code
generate solution and open it with visual 2019 (or in case of 5.3 it could be also vs2022)
the plugins won't build with one of the errors above

### Additional Information

TODO check also UE5.1
UE 5.4 works fine

_No response_
